from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.units import inch
import re

def clean_markdown(text):
    """Membersihkan simbol markdown agar rapi di PDF"""
    # Hapus tanda bintang ganda (bold)
    text = text.replace('**', '')
    # Hapus tanda bintang satu (list)
    text = text.replace('* ', '• ')
    # Hapus pagar (header)
    text = text.replace('### ', '').replace('## ', '').replace('# ', '')
    return text

def create_pdf_report(content_text):
    """Fungsi membuat PDF dari teks analisis"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    story = []

    # 1. Judul Laporan
    title_style = styles["Title"]
    story.append(Paragraph("Product Strategy Report", title_style))
    story.append(Spacer(1, 12))
    
    story.append(Paragraph("Generated by AI Product Strategist Agent", styles["Normal"]))
    story.append(Spacer(1, 24))

    # 2. Isi Laporan
    # Kita bersihkan markdown dulu
    clean_text = clean_markdown(content_text)
    
    # Pisahkan per baris untuk diproses
    lines = clean_text.split('\n')
    
    body_style = styles["BodyText"]
    body_style.fontSize = 11
    body_style.leading = 14 # Jarak antar baris

    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Logic sederhana untuk styling
        if "Tren" in line or "Analisis" in line or "Rekomendasi" in line or "Insight" in line:
            # Anggap ini sub-judul (Bold)
            heading_style = ParagraphStyle('HeadingCustom', parent=styles['Heading2'], spaceBefore=10, spaceAfter=5)
            story.append(Paragraph(line, heading_style))
        elif line.startswith("-") or line.startswith("•"):
            # List item
            story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;{line}", body_style))
        else:
            # Paragraf biasa
            story.append(Paragraph(line, body_style))
        
        story.append(Spacer(1, 4))

    # 3. Footer Disclaimer
    story.append(Spacer(1, 24))
    footer_style = styles["Italic"]
    footer_style.fontSize = 8
    footer_style.textColor = colors.gray
    story.append(Paragraph("Laporan ini dibuat secara otomatis oleh AI. Harap verifikasi data sebelum penggunaan strategis.", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer